# Generated by Django 5.2.15 on 2026-06-16 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('container_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('volume_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('ls_url', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('retired', 'retired')], default='active', max_length=16)),
                ('last_action', models.CharField(blank=True, max_length=64)),
                ('last_status', models.CharField(blank=True, max_length=32)),
                ('last_error', models.TextField(blank=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Directory name under the source root (e.g. dataset1).', max_length=255, unique=True)),
                ('source_uri', models.CharField(blank=True, help_text='Source images location. Blank -> <source_dir>/<name>.', max_length=1024)),
                ('target_uri', models.CharField(blank=True, help_text='Target output location. Blank -> <target_dir>/<name>.', max_length=1024)),
                ('storage_type', models.CharField(choices=[('local', 'local'), ('cloud', 'cloud')], default='local', max_length=16)),
                ('storage_root', models.CharField(blank=True, help_text='Cloud bucket root (required when storage is cloud).', max_length=1024)),
                ('classes', models.TextField(blank=True)),
                ('tools', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FleetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_port', models.PositiveIntegerField(default=8081, help_text='First host port; new annotators take the next free one.')),
                ('image_name', models.CharField(default='heartexlabs/label-studio:latest', max_length=255)),
                ('source_dir', models.CharField(default='data/source', help_text='Shared read-only source mount (relative to the project root or absolute).', max_length=512)),
                ('target_dir', models.CharField(default='data/target', help_text='Shared target mount where per-image txts + COCO are written.', max_length=512)),
                ('webhook_url', models.CharField(default='http://host.docker.internal:9000', help_text='Base URL each container POSTs annotation events to (the /hook receiver).', max_length=512)),
            ],
            options={
                'verbose_name': 'Fleet settings',
                'verbose_name_plural': 'Fleet settings',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ls_project_id', models.PositiveIntegerField(blank=True, null=True)),
                ('webhook_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('last_status', models.CharField(blank=True, max_length=32)),
                ('last_error', models.TextField(blank=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='fleet.annotator')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='fleet.dataset')),
            ],
            options={
                'ordering': ['dataset__name', 'annotator__username'],
                'unique_together': {('annotator', 'dataset')},
            },
        ),
    ]
