# Generated by Django 5.2.15 on 2026-06-27 16:05

import django.db.models.deletion
import training.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0003_dataset_has_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Experiment name; also the YAML 'name' and output dir prefix.", max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('epochs', models.PositiveIntegerField(default=100)),
                ('batch_size', models.PositiveIntegerField(default=4)),
                ('num_workers', models.PositiveIntegerField(default=4)),
                ('device', models.CharField(choices=[('auto', 'auto'), ('cuda', 'cuda'), ('cpu', 'cpu')], default='auto', max_length=16)),
                ('seed', models.IntegerField(default=42)),
                ('amp', models.BooleanField(default=False, help_text='Automatic mixed precision.')),
                ('gradient_clip_norm', models.FloatField(blank=True, null=True)),
                ('optimizer_name', models.CharField(choices=[('adamw', 'adamw'), ('adam', 'adam'), ('sgd', 'sgd')], default='adamw', max_length=16)),
                ('lr', models.FloatField(default=0.0001)),
                ('weight_decay', models.FloatField(default=0.0001)),
                ('optimizer_params', models.JSONField(blank=True, default=dict, help_text='Extra kwargs passed to the torch optimizer (e.g. momentum for sgd).')),
                ('scheduler_name', models.CharField(choices=[('none', 'none'), ('step', 'step'), ('multistep', 'multistep'), ('cosine', 'cosine'), ('exponential', 'exponential')], default='none', max_length=16)),
                ('scheduler_params', models.JSONField(blank=True, default=dict, help_text='Scheduler kwargs, e.g. {"step_size": 30, "gamma": 0.1}.')),
                ('eval_batch_size', models.PositiveIntegerField(default=4)),
                ('eval_num_workers', models.PositiveIntegerField(default=4)),
                ('eval_score_threshold', models.FloatField(default=0.001)),
                ('iou_thresholds', models.JSONField(blank=True, default=training.models.default_iou_thresholds)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configs_root', models.CharField(default='data/training/configs', help_text='Where generated experiment YAMLs are written (relative to the project root or absolute).', max_length=512)),
                ('runs_root', models.CharField(default='data/training/runs', help_text="Shared output root; each run's output_dir is runs_root/<name>-<id>.", max_length=512)),
                ('default_device', models.CharField(choices=[('auto', 'auto'), ('cuda', 'cuda'), ('cpu', 'cpu')], default='auto', max_length=16)),
                ('service_base_url', models.CharField(default='http://localhost:8200', help_text='Base URL of the friendy_chachkalica training service (unused until the execution phase).', max_length=512)),
            ],
            options={
                'verbose_name': 'Training settings',
                'verbose_name_plural': 'Training settings',
            },
        ),
        migrations.CreateModel(
            name='ExperimentDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('train', 'train'), ('val', 'val'), ('test', 'test')], default='train', max_length=8)),
                ('label_source', models.CharField(choices=[('source', 'source labels'), ('annotator', 'annotator output'), ('explicit', 'explicit path')], default='source', max_length=16)),
                ('explicit_labels_path', models.CharField(blank=True, help_text="Required when label source is 'explicit path'.", max_length=1024)),
                ('order', models.PositiveIntegerField(default=0)),
                ('annotator', models.ForeignKey(blank=True, help_text="Required when label source is 'annotator output'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.annotator')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.dataset')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='training.experiment')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arch', models.CharField(choices=[('retinanet', 'retinanet'), ('yolox', 'yolox'), ('rtdetr', 'rtdetr')], default='retinanet', max_length=32)),
                ('num_classes', models.PositiveIntegerField(blank=True, help_text="Leave blank for 'auto' (resolved per train dataset).", null=True)),
                ('params', models.JSONField(blank=True, default=dict, help_text='Architecture kwargs, e.g. {"variant": "resnet50_fpn_v2", "weights_backbone": "DEFAULT"}.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='training.experiment')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'created'), ('queued', 'queued'), ('running', 'running'), ('ok', 'ok'), ('error', 'error')], default='created', max_length=16)),
                ('config_yaml_path', models.CharField(blank=True, max_length=1024)),
                ('output_dir', models.CharField(blank=True, max_length=1024)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='training.experiment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
