# Generated by Django 5.2.15 on 2026-06-27 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_name', models.CharField(max_length=255)),
                ('run_index', models.IntegerField(blank=True, null=True)),
                ('model_arch', models.CharField(blank=True, max_length=32)),
                ('train_dataset_name', models.CharField(blank=True, max_length=255)),
                ('best_epoch', models.IntegerField(blank=True, null=True)),
                ('best_loss', models.FloatField(blank=True, null=True)),
                ('run_dir', models.CharField(blank=True, max_length=1024)),
                ('best_checkpoint', models.CharField(blank=True, max_length=1024)),
                ('last_checkpoint', models.CharField(blank=True, max_length=1024)),
                ('val_metrics', models.JSONField(blank=True, null=True)),
                ('test_metrics', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_results', to='training.trainingrun')),
            ],
            options={
                'ordering': ['run_index', 'id'],
                'unique_together': {('run', 'run_name')},
            },
        ),
    ]
