# Generated by Django 5.2.15 on 2026-06-27 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_dataset_has_labels'),
        ('training', '0002_runresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('dev', 'dev'), ('staging', 'staging'), ('production', 'production'), ('archived', 'archived')], default='dev', max_length=16)),
                ('arch', models.CharField(max_length=32)),
                ('checkpoint_path', models.CharField(max_length=1024)),
                ('num_classes', models.PositiveIntegerField(blank=True, null=True)),
                ('classes', models.JSONField(blank=True, default=list, help_text='Class names (ordered) the model predicts; needed to build eval configs.')),
                ('metrics', models.JSONField(blank=True, help_text='Metrics snapshot at promotion time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_run_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to='training.runresult')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EvalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_source', models.CharField(choices=[('source', 'source labels'), ('annotator', 'annotator output'), ('explicit', 'explicit path')], default='source', max_length=16)),
                ('explicit_labels_path', models.CharField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('created', 'created'), ('queued', 'queued'), ('running', 'running'), ('ok', 'ok'), ('error', 'error')], default='created', max_length=16)),
                ('request_yaml_path', models.CharField(blank=True, max_length=1024)),
                ('output_dir', models.CharField(blank=True, max_length=1024)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.annotator')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.dataset')),
                ('trained_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_runs', to='training.trainedmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
