# Generated by Django 5.2.15 on 2026-06-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_trainedmodel_evalrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentmodel',
            name='arch',
            field=models.CharField(choices=[('retinanet', 'retinanet'), ('yolox', 'yolox'), ('rtdetr', 'rtdetr'), ('rfdetr', 'rfdetr')], default='retinanet', max_length=32),
        ),
        migrations.AlterField(
            model_name='experimentmodel',
            name='num_classes',
            field=models.PositiveIntegerField(blank=True, help_text='Leave empty for auto — resolved per train dataset from its classes.txt. Only set this to override the class count.', null=True),
        ),
    ]
