# Generated by Django 5.2.15 on 2026-06-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_experimentmodel_arch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimentdataset',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='experimentmodel',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='experimentdataset',
            name='order',
        ),
        migrations.RemoveField(
            model_name='experimentmodel',
            name='order',
        ),
    ]
