# Generated by Django 5.2.15 on 2026-07-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_experimentdataset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentmodel',
            name='pretrained',
            field=models.BooleanField(default=False, help_text="Start from the architecture's published (COCO) pretrained weights instead of random init — adds weights=true to the generated config. An explicit 'weights' in params overrides this."),
        ),
    ]
