# Generated by Django 5.2.15 on 2026-07-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_experiment_eval_operating_nms_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentmodel',
            name='arch',
            field=models.CharField(choices=[('retinanet', 'retinanet'), ('yolox', 'yolox'), ('rtdetr', 'rtdetr'), ('rfdetr', 'rfdetr'), ('fasterrcnn', 'fasterrcnn')], default='retinanet', max_length=32),
        ),
    ]
